In [1]:
import numpy as np


In [20]:
ca=np.ones(shape=(100,5,5))

In [10]:
np.matrix(ca[12,15])*np.ones((5,1))


matrix([[ 5.],
        [ 5.],
        [ 5.],
        [ 5.],
        [ 5.]])

In [17]:
nc=50001

In [29]:
times=np.linspace(0,1,11)

In [31]:
b=times<0.5

In [41]:
times.searchsorted([0.5,0.91])

array([ 5, 10])

In [35]:
times

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])